apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcbot
  labels:
    app: gcbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcbot
  template:
    metadata:
      labels:
        app: gcbot
    spec:
      containers:
        - name: gcbot
          image: johnhopedawa/grocerylist:latest
          imagePullPolicy: Always
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gcbot-secret
                  key: API_TOKEN
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "150m"