apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocerylist-Deployment
  labels:
    app: gcbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcbot
  template:
    metadata:
      labels:
        app: gcbot
    spec:
      containers:
        - name: gcbot
          image: <image-name>:<tag>
          imagePullPolicy: Always
          
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "150m"
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3